#!/usr/bin/env python3
"""Generate Mermaid ontology maps and a graph-statistics report.

Every diagram is derived from the built RDF, not hand-drawn, so a map can never
drift out of step with the ontology it depicts.  Where a diagram would become
unreadable if fully expanded (the machine-element taxonomy has ~90 leaf types),
the generator prunes deliberately and states in the diagram itself what it
pruned, rather than silently showing a partial picture.

Outputs, into ``outputs/``:

``core_ontology_map.mmd``        Level 1 general design core
``mechanical_design_map.mmd``    Level 2 mechanical extension, incl. FBS wiring
``machine_element_map.mmd``      Level 3 machine-element families
``evidence_pipeline_map.mmd``    claim and evidence flow, with the review ladder
``substitution_model_map.mmd``   the reified substitution assessment
``graph_statistics.json``        NetworkX metrics over the merged graph
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set, Tuple

import yaml
from rdflib import Graph, Namespace, URIRef
from rdflib.namespace import OWL, RDF, RDFS, SKOS

LOG = logging.getLogger("generate_maps")
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG = REPO_ROOT / "config" / "config.yaml"

MDCORE = Namespace("https://w3id.org/mdkg/core#")
MECH = Namespace("https://w3id.org/mdkg/mechanical-design#")
MELEM = Namespace("https://w3id.org/mdkg/machine-elements#")
EV = Namespace("https://w3id.org/mdkg/evidence#")

NS_PREFIX = {
    str(MDCORE): "mdcore", str(MECH): "mech", str(MELEM): "melem", str(EV): "ev",
}


def local_name(iri: Any) -> str:
    """Return the local part of an IRI."""
    text = str(iri)
    return text.rsplit("#", 1)[-1] if "#" in text else text.rsplit("/", 1)[-1]


def node_id(iri: Any) -> str:
    """A Mermaid-safe node identifier."""
    for ns, prefix in NS_PREFIX.items():
        if str(iri).startswith(ns):
            return f"{prefix}_{local_name(iri)}"
    return local_name(iri).replace("-", "_")


def label_of(graph: Graph, iri: URIRef) -> str:
    """Human label for a node, falling back to its local name."""
    lbl = graph.value(iri, RDFS.label)
    text = str(lbl) if lbl else local_name(iri)
    return text.replace('"', "'")


def in_ns(iri: Any, ns: Namespace) -> bool:
    return str(iri).startswith(str(ns))


def subclass_edges(graph: Graph, ns: Namespace) -> List[Tuple[URIRef, URIRef]]:
    """Named subclass edges whose child lives in *ns*."""
    edges = []
    for child, parent in graph.subject_objects(RDFS.subClassOf):
        if not isinstance(child, URIRef) or not isinstance(parent, URIRef):
            continue
        if in_ns(child, ns):
            edges.append((child, parent))
    return edges


def write(path: Path, lines: Iterable[str]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines) + "\n"
    path.write_text(text, encoding="utf-8")
    LOG.info("wrote %s (%d lines)", path, text.count("\n"))
    return text.count("\n")


# ---------------------------------------------------------------------------
# Diagrams
# ---------------------------------------------------------------------------


def core_map(graph: Graph) -> List[str]:
    """Level 1: the general design core and how its parts connect."""
    lines = [
        "%% mdkg core ontology map (Level 1: general engineering design)",
        "%% Generated by scripts/generate_maps.py from ontology/core.ttl -- do not edit.",
        "%% Solid arrows are rdfs:subClassOf. Dashed arrows are the object properties",
        "%% that carry the model's meaning.",
        "graph TD",
        "  subgraph STRUCTURE[Structure]",
    ]
    for cls in ["DesignedArtifact", "TechnicalSystem", "Assembly", "Component",
                "Interface", "GeometryFeature", "DesignFeature", "Material"]:
        lines.append(f'    mdcore_{cls}["{cls}"]')
    lines += [
        "  end",
        "  subgraph FBS[Function - Behavior - Structure]",
        '    mdcore_Function["Function"]',
        '    mdcore_Behavior["Behavior"]',
        '    mdcore_PhysicalEffect["PhysicalEffect"]',
        '    mdcore_DesignAlternative["DesignAlternative"]',
        "  end",
        "  subgraph CONTEXT[Context and requirements]",
        '    mdcore_OperatingContext["OperatingContext"]',
        '    mdcore_OperatingCondition["OperatingCondition"]',
        '    mdcore_Requirement["Requirement"]',
        '    mdcore_Constraint["Constraint"]',
        '    mdcore_QuantityValue["QuantityValue"]',
        '    mdcore_ThresholdDefinition["ThresholdDefinition"]',
        "  end",
        "  subgraph DECISION[Decision and comparison]",
        '    mdcore_DesignProblem["DesignProblem"]',
        '    mdcore_CandidateSet["CandidateSet"]',
        '    mdcore_EvaluationCriterion["EvaluationCriterion"]',
        '    mdcore_AlternativeEvaluation["AlternativeEvaluation"]',
        '    mdcore_TradeOff["TradeOff"]',
        '    mdcore_DesignDecision["DesignDecision"]',
        '    mdcore_DecisionRationale["DecisionRationale"]',
        "  end",
        "  subgraph SUB[Substitution]",
        '    mdcore_SubstitutionAssessment["SubstitutionAssessment"]',
        '    mdcore_SubstitutionState["SubstitutionState"]',
        '    mdcore_DesignModification["DesignModification"]',
        "  end",
        "  subgraph FAILVER[Failure and verification]",
        '    mdcore_FailureMode["FailureMode"]',
        '    mdcore_FailureMechanism["FailureMechanism"]',
        '    mdcore_VerificationMethod["VerificationMethod"]',
        '    mdcore_AcceptanceCriterion["AcceptanceCriterion"]',
        "  end",
        "  subgraph RULE[Rule layer]",
        '    mdcore_DesignRule["DesignRule"]',
        '    mdcore_SelectionRule["SelectionRule"]',
        '    mdcore_SubstitutionRule["SubstitutionRule"]',
        '    mdcore_VerificationRule["VerificationRule"]',
        '    mdcore_ReviewState["ReviewState"]',
        "  end",
        "",
        "  %% taxonomy",
        "  mdcore_DesignedArtifact --> mdcore_TechnicalSystem",
        "  mdcore_DesignedArtifact --> mdcore_Assembly",
        "  mdcore_DesignedArtifact --> mdcore_Component",
        "  mdcore_DesignFeature --> mdcore_GeometryFeature",
        "  mdcore_Requirement --> mdcore_Constraint",
        "  mdcore_DesignRule --> mdcore_SelectionRule",
        "  mdcore_DesignRule --> mdcore_SubstitutionRule",
        "  mdcore_DesignRule --> mdcore_VerificationRule",
        "",
        "  %% function - behavior - structure",
        "  mdcore_Function -.->|realizedBy| mdcore_Behavior",
        "  mdcore_Behavior -.->|enabledBy| mdcore_DesignAlternative",
        "  mdcore_Behavior -.->|reliesOnEffect| mdcore_PhysicalEffect",
        "  mdcore_DesignAlternative -.->|performsFunction| mdcore_Function",
        "  mdcore_DesignedArtifact -.->|hasFunction| mdcore_Function",
        "  mdcore_Behavior -.->|behaviorRequiresCondition| mdcore_OperatingCondition",
        "",
        "  %% context and requirements",
        "  mdcore_OperatingContext -.->|hasCondition| mdcore_OperatingCondition",
        "  mdcore_Requirement -.->|hasTargetValue| mdcore_QuantityValue",
        "  mdcore_Requirement -.->|applicableIn| mdcore_OperatingContext",
        "  mdcore_ThresholdDefinition -.->|thresholdValue| mdcore_QuantityValue",
        "  mdcore_ThresholdDefinition -.->|thresholdContext| mdcore_OperatingContext",
        "",
        "  %% decision",
        "  mdcore_DesignProblem -.->|requiresFunction| mdcore_Function",
        "  mdcore_DesignProblem -.->|hasRequirement| mdcore_Requirement",
        "  mdcore_DesignProblem -.->|problemContext| mdcore_OperatingContext",
        "  mdcore_CandidateSet -.->|hasCandidate| mdcore_DesignAlternative",
        "  mdcore_CandidateSet -.->|candidateSetFor| mdcore_DesignProblem",
        "  mdcore_EvaluationCriterion -.->|derivedFrom| mdcore_Requirement",
        "  mdcore_AlternativeEvaluation -.->|evaluatesAlternative| mdcore_DesignAlternative",
        "  mdcore_AlternativeEvaluation -.->|againstCriterion| mdcore_EvaluationCriterion",
        "  mdcore_AlternativeEvaluation -.->|applicableContext| mdcore_OperatingContext",
        "  mdcore_DesignDecision -.->|selectsAlternative| mdcore_DesignAlternative",
        "  mdcore_DesignDecision -.->|hasRationale| mdcore_DecisionRationale",
        "  mdcore_DecisionRationale -.->|supportedByEvaluation| mdcore_AlternativeEvaluation",
        "",
        "  %% substitution -- reified, directional, never inferred",
        "  mdcore_SubstitutionAssessment -.->|candidate / baseline| mdcore_DesignAlternative",
        "  mdcore_SubstitutionAssessment -.->|functionBeingPreserved| mdcore_Function",
        "  mdcore_SubstitutionAssessment -.->|assessmentContext| mdcore_OperatingContext",
        "  mdcore_SubstitutionAssessment -.->|assessmentConclusion| mdcore_SubstitutionState",
        "  mdcore_SubstitutionAssessment -.->|requiredDesignModification| mdcore_DesignModification",
        "  mdcore_SubstitutionAssessment -.->|assessmentTradeOff| mdcore_TradeOff",
        "  mdcore_SubstitutionAssessment -.->|requiredVerification| mdcore_VerificationMethod",
        "",
        "  %% failure and verification",
        "  mdcore_DesignAlternative -.->|mayExperienceFailureMode| mdcore_FailureMode",
        "  mdcore_FailureMode -.->|causedByFailureMechanism| mdcore_FailureMechanism",
        "  mdcore_FailureMode -.->|aggravatedByCondition| mdcore_OperatingCondition",
        "  mdcore_FailureMode -.->|mitigatedByDesignFeature| mdcore_DesignFeature",
        "  mdcore_VerificationMethod -.->|addressesFailureMode| mdcore_FailureMode",
        "  mdcore_VerificationMethod -.->|hasAcceptanceCriterion| mdcore_AcceptanceCriterion",
        "",
        "  %% rules",
        "  mdcore_DesignRule -.->|ruleAppliesInContext| mdcore_OperatingContext",
        "  mdcore_DesignRule -.->|ruleConcernsFunction| mdcore_Function",
        "  mdcore_DesignRule -.->|reviewStatus| mdcore_ReviewState",
        "  mdcore_SubstitutionAssessment -.->|reviewStatus| mdcore_ReviewState",
        "",
        "  classDef sub fill:#eef4fb,stroke:#4a6f9a,stroke-width:1px;",
        "  classDef struct fill:#f6f2ea,stroke:#8a7a5c,stroke-width:1px;",
        "  class mdcore_SubstitutionAssessment,mdcore_SubstitutionState,mdcore_DesignModification sub;",
        "  class mdcore_DesignedArtifact,mdcore_TechnicalSystem,mdcore_Assembly,mdcore_Component struct;",
    ]
    return lines


def mechanical_map(graph: Graph) -> List[str]:
    """Level 2: the mechanical extension, and how a function reaches a structure."""
    lines = [
        "%% mdkg mechanical-design map (Level 2)",
        "%% Generated by scripts/generate_maps.py -- do not edit.",
        "%% Shows the Function -> Behavior -> Alternative chain that lets a designer",
        "%% search from a required function without knowing any element name.",
        "graph LR",
        "  subgraph L1[Level 1 core]",
        '    mdcore_DesignedArtifact["mdcore:DesignedArtifact"]',
        '    mdcore_Function["mdcore:Function"]',
        '    mdcore_Behavior["mdcore:Behavior"]',
        '    mdcore_LoadingCondition["mdcore:LoadingCondition"]',
        '    mdcore_KinematicCondition["mdcore:KinematicCondition"]',
        '    mdcore_FailureMode["mdcore:FailureMode"]',
        "  end",
        "  subgraph L2A[Mechanical artifacts and interfaces]",
        '    mech_MechanicalArtifact["MechanicalArtifact"]',
        '    mech_MechanicalSystem["MechanicalSystem"]',
        '    mech_MachineElement["MachineElement"]',
        '    mech_MechanicalInterface["MechanicalInterface"]',
        '    mech_ShaftHubInterface["ShaftHubInterface"]',
        '    mech_Keyseat["Keyseat"]',
        '    mech_StressRaiser["StressRaiser"]',
        '    mech_Fit["Fit / InterferenceFit / SlipFit"]',
        "  end",
        "  subgraph L2F[Mechanical functions]",
        '    mech_TransmitTorqueShaftToHub["TransmitTorqueShaftToHub"]',
        '    mech_PermitAxialMotion["PermitAxialMotion"]',
        '    mech_LocateAxially["LocateAxially"]',
        '    mech_LimitTransmittedTorque["LimitTransmittedTorque"]',
        '    mech_SupportRotatingShaft["SupportRotatingShaft"]',
        "  end",
        "  subgraph L2B[Mechanical behaviors]",
        '    mech_ShearLoadTransfer["ShearLoadTransfer"]',
        '    mech_BearingLoadTransfer["BearingLoadTransfer"]',
        '    mech_FrictionalLoadTransfer["FrictionalLoadTransfer"]',
        '    mech_DistributedToothContact["DistributedToothContact"]',
        '    mech_RollingContactSupport["RollingContactSupport"]',
        '    mech_HydrodynamicFilmSupport["HydrodynamicFilmSupport"]',
        "  end",
        "  subgraph L2C[Mechanical conditions]",
        '    mech_TorsionalLoading["TorsionalLoading"]',
        '    mech_BidirectionalRotation["BidirectionalRotation"]',
        '    mech_AxialSlidingUnderTorque["AxialSlidingUnderTorque"]',
        '    mech_Misalignment["Misalignment"]',
        "  end",
        "  subgraph L2FAIL[Mechanical failure and verification]",
        '    mech_ShearFailure["ShearFailure"]',
        '    mech_BearingCompressionFailure["BearingCompressionFailure"]',
        '    mech_FatigueFracture["FatigueFracture"]',
        '    mech_ConnectionSlip["ConnectionSlip"]',
        '    mech_Brinelling["Brinelling"]',
        '    mech_SurfacePitting["SurfacePitting"]',
        '    mech_ShearStressCheck["ShearStressCheck"]',
        '    mech_BearingStressCheck["BearingStressCheck"]',
        '    mech_BearingLifeCalculation["BearingLifeCalculation"]',
        "  end",
        "",
        "  mdcore_DesignedArtifact --> mech_MechanicalArtifact",
        "  mech_MechanicalArtifact --> mech_MechanicalSystem",
        "  mech_MechanicalArtifact --> mech_MachineElement",
        "  mech_MechanicalInterface --> mech_ShaftHubInterface",
        "  mdcore_LoadingCondition --> mech_TorsionalLoading",
        "  mdcore_KinematicCondition --> mech_AxialSlidingUnderTorque",
        "  mdcore_KinematicCondition --> mech_Misalignment",
        "  mdcore_LoadingCondition --> mech_BidirectionalRotation",
        "",
        "  mdcore_Function -.->|instances| mech_TransmitTorqueShaftToHub",
        "  mdcore_Behavior -.->|instances| mech_ShearLoadTransfer",
        "  mdcore_FailureMode -.->|instances| mech_ShearFailure",
        "",
        "  mech_TransmitTorqueShaftToHub -.->|realizedBy| mech_ShearLoadTransfer",
        "  mech_TransmitTorqueShaftToHub -.->|realizedBy| mech_BearingLoadTransfer",
        "  mech_TransmitTorqueShaftToHub -.->|realizedBy| mech_FrictionalLoadTransfer",
        "  mech_TransmitTorqueShaftToHub -.->|realizedBy| mech_DistributedToothContact",
        "  mech_SupportRotatingShaft -.->|realizedBy| mech_RollingContactSupport",
        "  mech_SupportRotatingShaft -.->|realizedBy| mech_HydrodynamicFilmSupport",
        "",
        "  mech_ShearLoadTransfer -.->|failsBy| mech_ShearFailure",
        "  mech_BearingLoadTransfer -.->|failsBy| mech_BearingCompressionFailure",
        "  mech_FrictionalLoadTransfer -.->|failsBy| mech_ConnectionSlip",
        "  mech_RollingContactSupport -.->|failsBy| mech_SurfacePitting",
        "  mech_RollingContactSupport -.->|failsBy| mech_Brinelling",
        "  mech_Keyseat -.->|is a| mech_StressRaiser",
        "  mech_StressRaiser -.->|initiates| mech_FatigueFracture",
        "",
        "  mech_ShearFailure -.->|verifiedBy| mech_ShearStressCheck",
        "  mech_BearingCompressionFailure -.->|verifiedBy| mech_BearingStressCheck",
        "  mech_SurfacePitting -.->|verifiedBy| mech_BearingLifeCalculation",
        "",
        "  mech_FrictionalLoadTransfer -.->|requires| mech_TorsionalLoading",
        "  mech_AxialSlidingUnderTorque -.->|excludes plain key, demands| mech_PermitAxialMotion",
    ]
    return lines


def machine_element_map(graph: Graph) -> List[str]:
    """Level 3: families, with the pilot family expanded and the rest pruned."""
    families = [
        "PowerTransmissionElement", "ConnectionElement", "SupportElement",
        "MotionGuidanceElement", "FasteningElement", "SealingElement",
        "EnergyStorageElement", "MotionControlElement",
    ]
    # Count leaves per family so the diagram can honestly state what it pruned.
    leaf_counts: Dict[str, int] = defaultdict(int)
    for child, parent in subclass_edges(graph, MELEM):
        leaf_counts[local_name(parent)] += 1

    lines = [
        "%% mdkg machine-element family map (Level 3)",
        "%% Generated by scripts/generate_maps.py -- do not edit.",
        "%% Families are organised by the FUNCTION a family delivers, not by the chapter",
        "%% that happens to describe it. Families are NOT disjoint: a tapered roller",
        "%% bearing both supports and locates; a setscrew both connects and fastens.",
        "graph TD",
        '  mech_MachineElement["mech:MachineElement"]',
    ]
    for fam in families:
        lines.append(f'  melem_{fam}["{fam}"]')
        lines.append(f"  mech_MachineElement --> melem_{fam}")

    lines += [
        "",
        "  %% ---- PILOT FAMILY, expanded ----",
        '  melem_ShaftHubConnectionElement["ShaftHubConnectionElement"]',
        "  melem_ConnectionElement --> melem_ShaftHubConnectionElement",
    ]
    for elem, parent in [
        ("Key", "ShaftHubConnectionElement"), ("ParallelKey", "Key"),
        ("SquareKey", "ParallelKey"), ("RectangularKey", "ParallelKey"),
        ("TaperKey", "Key"), ("GibHeadKey", "TaperKey"), ("WoodruffKey", "Key"),
        ("PinKey", "Key"), ("Spline", "ShaftHubConnectionElement"),
        ("StraightSidedSpline", "Spline"), ("InvoluteSpline", "Spline"),
        ("Pin", "ShaftHubConnectionElement"), ("StraightPin", "Pin"),
        ("TaperPin", "Pin"), ("SplitSpringPin", "Pin"), ("ShearPin", "Pin"),
        ("Setscrew", "ShaftHubConnectionElement"),
        ("InterferenceFitConnection", "ShaftHubConnectionElement"),
        ("PressFitConnection", "InterferenceFitConnection"),
        ("ShrinkFitConnection", "InterferenceFitConnection"),
        ("TaperedFitConnection", "ShaftHubConnectionElement"),
        ("ClampingHubConnection", "ShaftHubConnectionElement"),
        ("KeylessLockingAssembly", "ShaftHubConnectionElement"),
    ]:
        lines.append(f'  melem_{elem}["{elem}"]')
        lines.append(f"  melem_{parent} --> melem_{elem}")

    lines += [
        "  melem_Setscrew -.->|also a| melem_FasteningElement",
        "",
        "  %% ---- BEARINGS, partially expanded (second pilot family) ----",
        '  melem_Bearing["Bearing"]',
        "  melem_SupportElement --> melem_Bearing",
    ]
    for elem, parent in [
        ("RollingContactBearing", "Bearing"), ("BallBearing", "RollingContactBearing"),
        ("DeepGrooveBallBearing", "BallBearing"), ("RollerBearing", "RollingContactBearing"),
        ("CylindricalRollerBearing", "RollerBearing"), ("TaperedRollerBearing", "RollerBearing"),
        ("SphericalRollerBearing", "RollerBearing"), ("NeedleBearing", "RollerBearing"),
        ("PlainBearing", "Bearing"), ("JournalBearing", "PlainBearing"),
    ]:
        lines.append(f'  melem_{elem}["{elem}"]')
        lines.append(f"  melem_{parent} --> melem_{elem}")

    lines += [
        "",
        "  %% ---- REMAINING FAMILIES, deliberately pruned to one level ----",
        f'  melem_gears["Gear + 4 subtypes"]',
        f'  melem_flex["FlexibleDriveElement + 5 subtypes"]',
        f'  melem_coup["Coupling + 3 subtypes"]',
        f'  melem_fast["Fastener + 5 subtypes"]',
        f'  melem_spr["Spring + 5 subtypes"]',
        f'  melem_seal["Seal + 5 subtypes"]',
        f'  melem_lin["LinearMotionElement + 3 subtypes"]',
        f'  melem_cb["Clutch / Brake / Flywheel"]',
        f'  melem_shaft["Shaft / Axle / RetainingRing / Collar"]',
        "  melem_PowerTransmissionElement --> melem_gears",
        "  melem_PowerTransmissionElement --> melem_flex",
        "  melem_ConnectionElement --> melem_coup",
        "  melem_FasteningElement --> melem_fast",
        "  melem_EnergyStorageElement --> melem_spr",
        "  melem_SealingElement --> melem_seal",
        "  melem_MotionGuidanceElement --> melem_lin",
        "  melem_MotionControlElement --> melem_cb",
        "  melem_PowerTransmissionElement --> melem_shaft",
        "",
        f"  %% PRUNING NOTE: {sum(leaf_counts.values())} subclass edges exist in",
        "  %% ontology/machine-elements.ttl. Only the two pilot families are expanded",
        "  %% here; the rest are collapsed into single nodes stating their subtype count.",
        "",
        "  classDef pilot fill:#eef4fb,stroke:#4a6f9a,stroke-width:2px;",
        "  classDef pruned fill:#f4f4f4,stroke:#999,stroke-dasharray:4 3;",
        "  class melem_ShaftHubConnectionElement,melem_Bearing pilot;",
        "  class melem_gears,melem_flex,melem_coup,melem_fast,melem_spr,melem_seal,melem_lin,melem_cb,melem_shaft pruned;",
    ]
    return lines


def evidence_pipeline_map(graph: Graph) -> List[str]:
    """The claim/evidence flow, with real counts from the built graph."""
    n_spans = len(set(graph.subjects(RDF.type, EV.EvidenceSpan)))
    n_claims = len(set(graph.subjects(RDF.type, EV.NormalizedClaim)))
    n_pages = len(set(graph.subjects(RDF.type, EV.Page)))
    n_align = len(set(graph.subjects(RDF.type, EV.ClaimAlignment)))
    n_rules = sum(
        len(set(graph.subjects(RDF.type, cls)))
        for cls in (MDCORE.SelectionRule, MDCORE.SubstitutionRule, MDCORE.VerificationRule)
    )
    n_verified = len(set(graph.subjects(MDCORE.reviewStatus, MDCORE.HumanVerified)))

    return [
        "%% mdkg evidence and claim pipeline",
        "%% Generated by scripts/generate_maps.py -- counts are live from build/mdkg-full.ttl.",
        "flowchart TD",
        '  PDF["Source PDF<br/>identified by SHA-256"]',
        '  EXTRACT["extract_pdf_structure.py<br/>pages, blocks, bboxes, outline,<br/>math-font ratio per page"]',
        '  SEED["data/evidence_seeds.yaml<br/>analyst writes: doc + page index + anchor phrase"]',
        f'  SPAN["ev:EvidenceSpan<br/>{n_spans} verified<br/>pdfPageIndex AND printedPage,<br/>kept as separate fields"]',
        f'  PAGE["ev:Page<br/>{n_pages} pages cited"]',
        '  CSEED["data/claims_seed.yaml<br/>normalized statement, conditions,<br/>assumptions, quantities+units"]',
        f'  CLAIM["ev:NormalizedClaim<br/>{n_claims} claims"]',
        f'  ALIGN["ev:ClaimAlignment<br/>{n_align} cross-book alignments"]',
        '  CAND["ev:CandidateDesignRule<br/>(proposed, not accepted)"]',
        f'  RULE["mdcore:DesignRule<br/>{n_rules} in rules/*.yaml"]',
        '  AXIOM["OWL axiom or executable rule"]',
        "",
        "  PDF --> EXTRACT --> SEED",
        '  SEED -->|"build_evidence_spans.py<br/>FAILS if the anchor is not<br/>on the stated page"| SPAN',
        "  SPAN --> PAGE",
        '  CSEED -->|"build_claims.py<br/>joins claim to span;<br/>rejects unevidenced claims"| CLAIM',
        "  SPAN -->|supportedByEvidence| CLAIM",
        "  CLAIM --> ALIGN",
        "  CLAIM --> CAND",
        '  CAND -->|"HUMAN REVIEW GATE"| RULE',
        '  RULE -->|"human sign-off"| AXIOM',
        "",
        "  subgraph LADDER[Review ladder - automated stages may not exceed NeedsReview]",
        '    R1["AutomaticallyExtracted"] --> R2["Normalized"] --> R3["NeedsReview"]',
        '    R3 -.->|"human only"| R4["HumanVerified"]',
        '    R3 -.->|"human only"| R5["Rejected"]',
        "  end",
        f'  NOTE["v0.1 status: all {n_claims} claims at NeedsReview<br/>{n_verified} HumanVerified, pending sign-off"]',
        "  CLAIM -.-> NOTE",
        "  R3 -.-> NOTE",
        "",
        "  subgraph GUARD[Anti-fabrication guarantees]",
        '    G1["Anchors re-verified against the PDF on every build"]',
        '    G2["Citations assembled from stored fields, never composed"]',
        '    G3["printedPage never computed from pdfPageIndex"]',
        '    G4["Excerpts from glyph-mismapped text flagged, never quoted"]',
        "  end",
        "  SPAN -.-> GUARD",
        "",
        "  classDef gate fill:#fdf0e6,stroke:#c07830,stroke-width:2px;",
        "  classDef guard fill:#eef7ee,stroke:#4a8a4a;",
        "  class CAND,RULE gate;",
        "  class G1,G2,G3,G4 guard;",
    ]


def substitution_model_map(graph: Graph) -> List[str]:
    """The reified substitution assessment, with the live verdict distribution."""
    verdicts: Dict[str, int] = defaultdict(int)
    for _, concl in graph.subject_objects(MDCORE.assessmentConclusion):
        verdicts[local_name(concl)] += 1
    verdict_line = ", ".join(f"{k}: {v}" for k, v in sorted(verdicts.items())) or "none"

    return [
        "%% mdkg substitution assessment model",
        "%% Generated by scripts/generate_maps.py -- verdict counts are live.",
        "%% Substitution is NOT an edge between two alternatives. The assessment is the",
        "%% individual; the two alternatives are two of its arguments.",
        "graph TD",
        '  SA(["mdcore:SubstitutionAssessment"])',
        '  CAND["candidateAlternative"]',
        '  BASE["baselineAlternative"]',
        '  FUNC["functionBeingPreserved<br/>MANDATORY"]',
        '  CTX["assessmentContext<br/>MANDATORY"]',
        '  REQ_A["applicableRequirement"]',
        '  REQ_S["satisfiedRequirement"]',
        '  REQ_V["violatedRequirement"]',
        '  COND["assessmentCondition"]',
        '  MOD["requiredDesignModification"]',
        '  IFACE["interfaceCompatibility"]',
        '  ADV["assessmentAdvantage"]',
        '  DIS["assessmentDisadvantage"]',
        '  TO["assessmentTradeOff"]',
        '  FIN["introducedFailureMode"]',
        '  FMIT["mitigatedFailureMode"]',
        '  VER["requiredVerification"]',
        '  CONF["confidence + reviewStatus"]',
        '  EVID["supportedByEvidence"]',
        '  CONCL{{"assessmentConclusion"}}',
        "",
        "  SA --> CAND", "  SA --> BASE", "  SA --> FUNC", "  SA --> CTX",
        "  SA --> REQ_A", "  SA --> REQ_S", "  SA --> REQ_V",
        "  SA --> COND", "  SA --> MOD", "  SA --> IFACE",
        "  SA --> ADV", "  SA --> DIS", "  SA --> TO",
        "  SA --> FIN", "  SA --> FMIT", "  SA --> VER",
        "  SA --> CONF", "  SA --> EVID", "  SA --> CONCL",
        "",
        "  subgraph STATES[Six mutually exclusive verdicts]",
        '    S1["NotAnAlternative<br/>function or interface not preserved"]',
        '    S2["FunctionalAlternative<br/>shares a function; NOT interchangeable"]',
        '    S3["ConditionallySubstitutable<br/>requires >=1 condition or modification"]',
        '    S4["DirectlySubstitutable<br/>identical interface, no redesign"]',
        '    S5["PreferredAlternative<br/>relative to a stated requirement set"]',
        '    S6["InsufficientEvidence<br/>sources do not settle it"]',
        "  end",
        "  CONCL --> S1", "  CONCL --> S2", "  CONCL --> S3",
        "  CONCL --> S4", "  CONCL --> S5", "  CONCL --> S6",
        "",
        "  subgraph PROHIB[Prohibited inferences - enforced by validate_ontology.py]",
        '    P1["NO symmetry:<br/>A replaces B does not give B replaces A"]',
        '    P2["NO transitivity:<br/>A-&gt;B and B-&gt;C does not give A-&gt;C"]',
        '    P3["NO defaulting:<br/>shared function yields at most FunctionalAlternative"]',
        '    P4["DirectlySubstitutable needs positive<br/>interface + requirement evidence"]',
        "  end",
        "  SA -.-> PROHIB",
        "",
        '  DEMO["v0.1 worked example:<br/>SA-001 spline replaces key = PreferredAlternative<br/>SA-006 key replaces spline = NotAnAlternative<br/>SAME pair, SAME context, opposite verdicts"]',
        "  P1 -.-> DEMO",
        f'  LIVE["Verdicts in the current graph:<br/>{verdict_line}"]',
        "  CONCL -.-> LIVE",
        "",
        "  classDef mand fill:#fdf0e6,stroke:#c07830,stroke-width:2px;",
        "  classDef prohib fill:#fbeeee,stroke:#a44;",
        "  class FUNC,CTX,CONCL mand;",
        "  class P1,P2,P3,P4 prohib;",
    ]


# ---------------------------------------------------------------------------
# Statistics
# ---------------------------------------------------------------------------


def graph_statistics(graph: Graph) -> Dict[str, Any]:
    """NetworkX metrics over the merged graph, for a structural sanity check."""
    try:
        import networkx as nx
    except ImportError:
        return {"error": "networkx unavailable"}

    dg = nx.DiGraph()
    for s, p, o in graph:
        if isinstance(s, URIRef) and isinstance(o, URIRef):
            dg.add_edge(str(s), str(o), predicate=str(p))

    degrees = sorted(dg.degree, key=lambda kv: -kv[1])[:15]
    undirected = dg.to_undirected()
    components = list(nx.connected_components(undirected)) if undirected.number_of_nodes() else []

    return {
        "nodes": dg.number_of_nodes(),
        "edges": dg.number_of_edges(),
        "connected_components": len(components),
        "largest_component_size": max((len(c) for c in components), default=0),
        "isolated_nodes": len(list(nx.isolates(dg))),
        "most_connected": [{"node": n, "degree": d} for n, d in degrees],
        "note": (
            "A single dominant component is expected: the TBox, the claims and the "
            "assessments are meant to be reachable from one another. Isolated nodes "
            "indicate vocabulary that nothing yet uses."
        ),
    }


def run(config: Dict[str, Any]) -> Dict[str, Any]:
    build_dir = REPO_ROOT / config["paths"]["build_dir"]
    out_dir = REPO_ROOT / config["paths"]["outputs_dir"]
    full = build_dir / "mdkg-full.ttl"
    if not full.exists():
        raise SystemExit(f"{full} missing; run scripts/build_ontology.py first")

    graph = Graph()
    graph.parse(full, format="turtle")
    LOG.info("loaded %d triples", len(graph))

    written = {
        "core_ontology_map.mmd": write(out_dir / "core_ontology_map.mmd", core_map(graph)),
        "mechanical_design_map.mmd": write(out_dir / "mechanical_design_map.mmd", mechanical_map(graph)),
        "machine_element_map.mmd": write(out_dir / "machine_element_map.mmd", machine_element_map(graph)),
        "evidence_pipeline_map.mmd": write(out_dir / "evidence_pipeline_map.mmd", evidence_pipeline_map(graph)),
        "substitution_model_map.mmd": write(out_dir / "substitution_model_map.mmd", substitution_model_map(graph)),
    }
    stats = graph_statistics(graph)
    (out_dir / "graph_statistics.json").write_text(
        json.dumps(stats, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return {"diagrams": written, "graph_statistics": {k: v for k, v in stats.items() if k != "most_connected"}}


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)-7s %(name)s: %(message)s",
    )
    with args.config.open(encoding="utf-8") as fh:
        config = yaml.safe_load(fh)
    print(json.dumps(run(config), indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
